import Head from "next/head";
import {useRouter} from "next/router";

export default function Home() {
  const router = useRouter()
  router.push("/login")

  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
