import Head from "next/head";

function HomeCont() {
  return (
    <h1>you</h1>
  );
}


export default function Home() {
  return <HomeCont/>;
}



// import Head from "next/head";

// export default function Home() {
//   return (
//     <Head>
//       <title>Create Next App</title>
//       <meta name="description" content="Generated by create next app" />
//       <link rel="icon" href="/favicon.ico" />
//     </Head>
//   );
// }



